### ISSUE TITLE
credentials.get() can not be resolved

### ISSUE THREAD

**Issue by stefan-s29** [seu-as-code/seu-as-code.archetype#10]
I included a repository in the current archetype that requires credentials. The call to credentials.get('nexusUsername') could not be resolved, but resulted in the following error message instead:

"A problem occurred evaluating root project 'seuac-archetype'. > No signature of method: org.gradle.api.internal.artifacts.repositories.DefaultPasswordCredentials_Decorated.get() is applicable for argument types: (java.lang.String) values: [nexusUsername] Possible solutions: getAt(java.lang.String), grep(), grep(java.lang.Object), wait(), any(), wait(long)"

However, the credentials can still be acquired by the following more verbose call:
"username project.getExtensions().getExtraProperties().get('credentials').get('nexusUsername')"

**Comment by lreimer** [comment]
We should move this issue to the plugins repository since it is a bug of the credentials plugin. Of course we need to upgrade the archetype as well.

**Comment by phxql** [comment]
Fixed this in https://github.com/seu-as-code/seu-as-code.plugins/pull/23. And here: https://github.com/seu-as-code/seu-as-code.archetype/pull/11
